### ISSUE TITLE
Where is the description about source 'KG', 'NEL', 'COREF', 'WIKI'?

### ISSUE THREAD

**Issue by izuna385** [rloganiv/linked-wikitext-2#3]
Is there any detail descriptions of source?
I'm checking your [examples](https://rloganiv.github.io/linked-wikitext-2/#/explore), papers and raw datasets, but can't find about details of `source`.
(In [examples](https://rloganiv.github.io/linked-wikitext-2/#/explore) or raw datasets, `'WIKI', 'NEL', 'COREF', 'KG'` I mean.)

If you'd know details about `source` and write them, I'd appreciate it much.
Thanks.

**Comment by rloganiv** [comment]
Hi @izuna385,

The sources are described in Section 3 of our paper, although not in great detail. Here is what they mean:
- `WIKI` indicates that the mention is generated from a Wikipedia URL,
- `NEL` indicates that the mention is predicted by the [neural-el](https://github.com/nitishgupta/neural-el) entity linker
- `COREF` indicates that the mention was detected using [Stanford CoreNLP's](https://stanfordnlp.github.io/CoreNLP/) coreference resolution system, and the link was propagated from another mention in the cluster.
- `KG` indicates that the mention is related to a previously mentioned entity in the knowledge graph, and was detected using string matching.

We've released our code used to produce these annotations at: https://github.com/rloganiv/kglm-data.
I recommend checking out the documentation there for more details.

**Comment by izuna385** [comment]
Thanks and sorry for my being not careful. I'll check paper.
